export {
    notifyLogin,
    notifyLogout,
    registerAuthLifecycleHooks,
    resetAuthLifecycleHooks,
    type AuthLifecycleHooks,
} from './authLifecycle.ts';
export {
    createEdgeFunctionInvoker,
    EdgeFunctionError,
    type EdgeFunctionDeps,
    type EdgeFunctionInvoker,
    type EdgeSession,
} from './edgeFunctions.ts';
export {
    clamp,
    nonNegativeInteger,
    nonNegativeRatio,
    positiveInteger,
} from './numeric.ts';
export { getHpDisplayState, type HpDisplayState } from './hp.ts';
export {
    ACHIEVEMENTS,
    getAchievementProgress,
    getUnlockedTitles,
    type AchievementDefinition,
    type AchievementMetric,
    type AchievementProgress,
    type AchievementSnapshot,
} from './achievements.ts';
export { clampString } from './validation.ts';
export {
    filterAndSortInventory,
    type FilterAndSortInventoryOptions,
    type InventoryRarityFilter,
    type InventorySlotFilter,
    type InventorySortMode,
} from './inventory.ts';
export {
    filterHelpSections,
    HELP_SECTIONS,
    type HelpSection,
} from './help.ts';
export {
    appendHabitActivity,
    appendTaskXp,
    keepRecentEntries,
    MAX_STATS_DAILY_VALUE,
    MAX_STATS_LOG_ENTRIES,
    sanitizeHabitLog,
    sanitizeTaskXpLog,
    seedStatsLogFromCollections,
    type HabitLog,
    type TaskXpLog,
} from './statsLog.ts';
export {
    buildHabitReminderNotification,
    buildTaskDeadlineNotification,
    NOTIFICATION_CONFIG,
    NOTIFICATION_TEXT_MAX,
    resolveHabitReminderHour,
    selectDueSoonTasks,
    shouldSendHabitReminder,
    type DueSoonTask,
    type NotificationContent,
} from './notifications.ts';
export {
    getJstHour,
    getTodayJst,
    isOverdue,
    isValidYmd,
    shiftDate,
    toIsoDatePart,
} from './dates.ts';
export {
    BATTLE_SKILL_CONFIG,
    BATTLE_SKILLS,
    findBattleSkill,
    getUnlockedBattleSkills,
    resolveBattleSkill,
    type BattleSkillContext,
    type BattleSkillDefinition,
    type BattleSkillResolution,
    type BattleSkillType,
} from './battleSkills.ts';
export {
    createPersistStorageEnvelope,
    createSafePersistMerge,
    isPersistedStateRecord,
    isPersistStorageEnvelope,
    parsePersistStorageEnvelope,
    readPersistedStateRecord,
    readPersistStorageEnvelope,
    serializePersistStorageEnvelope,
    type NormalizedPersistStorageEnvelope,
    type PersistedStateRecord,
    type PersistStorageEnvelope,
} from './persist.ts';
export {
    addRecurrenceInterval,
    addSubtaskToTask,
    buildNextRecurringTask,
    createTask,
    getSubtaskRewardXp,
    hasOpenRecurringDuplicate,
    removeSubtaskFromTask,
    removeTask,
    sanitizeTaskCollection,
    TASK_LIMITS,
    toggleSubtask,
    toggleTaskCompletion,
    type NextRecurringTaskInput,
    type RemoveSubtaskResult,
    type ToggleSubtaskResult,
    type CreateTaskInput,
    type Priority,
    type Recurrence,
    type Subtask,
    type Task,
} from './tasks.ts';
export {
    areAllHabitsComplete,
    createHabit,
    DEFAULT_HABIT_CATEGORY_ID,
    getHabitCategoryById,
    getHabitCategoryByIdOrDefault,
    getHabitCompletionRate,
    getHabitStreak,
    HABIT_CATEGORIES,
    HABIT_LIMITS,
    HABIT_STREAK_LOOKBACK_DAYS,
    isRestDayOn,
    markRestDay,
    sanitizeRestDays,
    removeHabitData,
    sanitizeHabitCollection,
    sanitizeHabitRecords,
    toggleHabitDailyRecord,
    type Habit,
    type HabitCategory,
    type HabitDailyRecord,
    type HabitStatsInput,
    type RestDay,
} from './habits.ts';
export {
    cloudCursorKey,
    cloudOutboxKey,
    createCloudPullRunner,
    type CloudPullDeps,
    type CloudPullRunner,
    type PullBatch,
} from './cloudPull.ts';
export {
    createSyncCursor,
    SYNC_CURSOR_KEY,
    writeCanonicalSnapshot,
    type CanonicalWriteResult,
    type CanonicalWriteStatus,
    type SyncCursor,
} from './canonicalSync.ts';
export {
    DARK_THEME,
    FONT_SANS,
    LIGHT_THEME,
    themeToCssVariables,
    type ThemePalette,
} from './designTokens.ts';
export {
    LEGACY_STORAGE_KEYS,
    migrateLegacyQuestBoardData,
    MIGRATION_JOURNAL_KEY,
    MIGRATION_JOURNAL_VERSION,
    type LegacyMigrationOptions,
    type LegacyStorageReader,
    type MigrationJournal,
    type MigrationReport,
    type MigrationSection,
    type MigrationSectionResult,
    type MigrationSectionStatus,
} from './legacyMigration.ts';
export {
    convertLegacyHabitSnapshot,
    convertLegacyGameSnapshot,
    convertLegacyTaskSnapshot,
    sanitizeCanonicalGameSnapshot,
    sanitizeCanonicalHabitSnapshot,
    sanitizeCanonicalTaskSnapshot,
    SYNC_SNAPSHOT_LIMITS,
    SYNC_SNAPSHOT_VERSION,
    type CanonicalHabitSnapshot,
    type CanonicalBattleProgress,
    type CanonicalDebuffState,
    type CanonicalGameSnapshot,
    type CanonicalTaskSnapshot,
    type LegacyGameSnapshotSources,
} from './syncSnapshots.ts';
export {
    CANONICAL_STORAGE_KEYS,
    createCanonicalSnapshotRepositories,
    createSnapshotRepository,
    SNAPSHOT_REPOSITORY_VERSION,
    type CanonicalSnapshotRepositories,
    type RepositoryLoadResult,
    type RepositoryRemoveResult,
    type RepositorySaveResult,
    type RepositoryStorage,
    type RepositoryStorageResult,
    type RepositoryWriteFailure,
    type SnapshotRepository,
    type SnapshotRepositoryEnvelope,
    type SnapshotRepositoryOptions,
    type VersionedSnapshot,
} from './syncRepository.ts';
export {
    calculateEffectiveEquipmentStats,
    createEquipmentFromTemplate,
    EQUIPMENT_RARITIES,
    EQUIPMENT_SLOTS,
    getBestEquipmentIdsBySlot,
    getDominantEquipmentSlots,
    getEquipmentScore,
    getEquipmentSellXp,
    getNextEquipmentRarity,
    selectSynthesisIngredients,
    type BaseCharacterStats,
    type EffectiveStats,
    type Equipment,
    type EquipmentSlot,
    type EquipmentTemplate,
    type Rarity,
    type SynthesisSelection,
} from './equipment.ts';
export {
    capChestQueue,
    capEquipmentCollection,
    claimHabitAllCompleteBonus,
    claimSubtaskReward,
    claimTaskReward,
    createEmptyRewardLedger,
    createInitialCharacterState,
    createInitialGameStateSnapshot,
    GAME_STATE_LIMITS,
    sanitizeCharacterState,
    sanitizeChestQueue,
    sanitizeChestReward,
    sanitizeEquipmentCollection,
    sanitizeEquipmentItem,
    sanitizeGameStateSnapshot,
    sanitizeRewardLedger,
    type AvatarId,
    type CharacterState,
    type GameStateSnapshot,
    type RewardClaim,
    type RewardLedger,
} from './gameState.ts';
export {
    EQUIPMENT_POOL,
    GACHA_CONFIG,
    getMilestoneAtCount,
    rollEquipmentTemplate,
    SELL_XP_BY_RARITY,
    SYNTHESIS_CONFIG,
    type ChestReward,
    type ChestType,
    type GachaMilestone,
} from './rewards.ts';
export {
    buildHabitActivityByDate,
    buildTaskXpByDate,
    generateDateRange,
    getHabitHeatmapLevel,
    getMonthLabels,
    getTaskHeatmapLevel,
    groupDatesByWeeks,
    type HabitDayActivity,
} from './stats.ts';
export {
    applyCharacterXp,
    calculateLevel,
    calculateNextLevelXp,
    calculateXpProgress,
    CHARACTER_CONFIG,
    MAX_TOTAL_XP,
    XP_CONFIG,
    type ApplyCharacterXpResult,
    type CharacterProgressionState,
    type CharacterStatGains,
} from './progression.ts';
