/**
 * 共有画像アセットのマニフェスト（#498、ADR-006: ビルド時バンドル配布）。
 * キーはファイル名から拡張子を除いたもの。Web/Mobileはこのキーで同一画像を参照する。
 * 実際の読み込みは各プラットフォームのバンドラが行う:
 * - Web: `import x from '@life-quest/assets/images/<path>'`（Vite）
 * - Mobile: `require('../../..../packages/assets/images/<path>')`（Metro、#499で適用）
 * キーとファイルの整合は manifest.test.ts がビルド時に検証する。
 */
export const IMAGE_MANIFEST = {
    bg_battle_castle: 'images/bg_battle_castle.png',
    bg_battle_deep_sea: 'images/bg_battle_deep_sea.png',
    bg_battle_grassland: 'images/bg_battle_grassland.png',
    bg_battle_heaven: 'images/bg_battle_heaven.png',
    bg_castle: 'images/bg_castle.png',
    bg_deep_sea: 'images/bg_deep_sea.png',
    bg_grassland: 'images/bg_grassland.png',
    bg_heaven: 'images/bg_heaven.png',
    chest_blue: 'images/chest_blue.png',
    chest_gold: 'images/chest_gold.png',
    chest_rainbow: 'images/chest_rainbow.png',
    chest_red_gold: 'images/chest_red_gold.png',
    chest_silver: 'images/chest_silver.png',
    chest_wood: 'images/chest_wood.png',
    enemy_angel: 'images/enemy_angel.png',
    enemy_archangel: 'images/enemy_archangel.png',
    enemy_bat: 'images/enemy_bat.png',
    enemy_boar: 'images/enemy_boar.png',
    enemy_cherub: 'images/enemy_cherub.png',
    enemy_death_knight: 'images/enemy_death_knight.png',
    enemy_demon: 'images/enemy_demon.png',
    enemy_gargoyle: 'images/enemy_gargoyle.png',
    enemy_ghost: 'images/enemy_ghost.png',
    enemy_goblin: 'images/enemy_goblin.png',
    enemy_god_of_light: 'images/enemy_god_of_light.png',
    enemy_golem: 'images/enemy_golem.png',
    enemy_griffin: 'images/enemy_griffin.png',
    enemy_holy_knight: 'images/enemy_holy_knight.png',
    enemy_killer_shark: 'images/enemy_killer_shark.png',
    enemy_kraken: 'images/enemy_kraken.png',
    enemy_leviathan: 'images/enemy_leviathan.png',
    enemy_light_elemental: 'images/enemy_light_elemental.png',
    enemy_living_armor: 'images/enemy_living_armor.png',
    enemy_merman: 'images/enemy_merman.png',
    enemy_minotaur: 'images/enemy_minotaur.png',
    enemy_orc: 'images/enemy_orc.png',
    enemy_pegasus: 'images/enemy_pegasus.png',
    enemy_rabbit: 'images/enemy_rabbit.png',
    enemy_sea_serpent: 'images/enemy_sea_serpent.png',
    enemy_seraph: 'images/enemy_seraph.png',
    enemy_siren: 'images/enemy_siren.png',
    enemy_skeleton: 'images/enemy_skeleton.png',
    enemy_slime: 'images/enemy_slime.png',
    enemy_snake: 'images/enemy_snake.png',
    enemy_treant: 'images/enemy_treant.png',
    enemy_valkyrie: 'images/enemy_valkyrie.png',
    enemy_vampire: 'images/enemy_vampire.png',
    enemy_water_dragon: 'images/enemy_water_dragon.png',
    enemy_water_elemental: 'images/enemy_water_elemental.png',
    enemy_wight: 'images/enemy_wight.png',
    enemy_wolf: 'images/enemy_wolf.png',
    enemy_zombie: 'images/enemy_zombie.png',
    hero: 'images/hero.png',
    hero_male: 'images/hero_male.png',
    item_aegis_shield: 'images/item_aegis_shield.png',
    item_chain_mail: 'images/item_chain_mail.png',
    item_dragon_armor: 'images/item_dragon_armor.png',
    item_excalibur: 'images/item_excalibur.png',
    item_gold_amulet: 'images/item_gold_amulet.png',
    item_iron_sword: 'images/item_iron_sword.png',
    item_leather_armor: 'images/item_leather_armor.png',
    item_mystic_staff: 'images/item_mystic_staff.png',
    item_phoenix_ring: 'images/item_phoenix_ring.png',
    item_plate_armor: 'images/item_plate_armor.png',
    item_ring_of_god: 'images/item_ring_of_god.png',
    item_silver_ring: 'images/item_silver_ring.png',
    item_steel_blade: 'images/item_steel_blade.png',
    item_wooden_ring: 'images/item_wooden_ring.png',
    item_wooden_sword: 'images/item_wooden_sword.png',
    slime: 'images/slime.png',
    weapon_iron: 'images/weapon_iron.png',
} as const;

export type ImageKey = keyof typeof IMAGE_MANIFEST;

export const IMAGE_KEYS = Object.keys(IMAGE_MANIFEST) as ImageKey[];
